### ISSUE TITLE
Group-Co 目前只支持PHP5.6么？

### ISSUE THREAD

**Issue by peterpang55** [fucongcong/Group-Co#5]
您好，看了下Group_Co的环境依赖，目前Group_CO只支持PHP5.6么？还是也支持PHP7。

**Comment by fucongcong** [comment]
支持php7的，不过需要把phpunit的版本切换到支持php7。现在phpunit版本是4.*的。

**Comment by fucongcong** [comment]
最新版本已经将phpunit依赖升到5.7.同时支持5.6.7.0.7.1

**Comment by peterpang55** [comment]
好的，谢谢～
