### ISSUE TITLE
太好了，終於找到除amphp以外另一個看上去比較可以的異步框架了

### ISSUE THREAD

**Issue by shtse8** [fucongcong/Group-Co#6]
我現在還是大量使用`amphp`作為異步框架，因為只有`amphp`是採用`yield`寫法，而不是`then`。
想請問一下如果要從amphp轉過來有甚麼需要注意的地方呢？

**Comment by fucongcong** [comment]
group-co 的使用其实和传统同步框架类似，只有在异步的地方需要使用yield关键字做协程切换。
具体可以看看readme和跑一下demo

**Comment by moss1993** [comment]
有使用详细文档吗？小白想跟大神学习下。
