### ISSUE TITLE
PHP7下，接照文档的部署下来，登录和注册都失败

### ISSUE THREAD

**Issue by birdy0815** [fucongcong/Group-Co#8]
root      2991  0.0  0.0 485516  7820 ?        Ssl  11:44   0:00 php user: master    
root      2992  0.0  0.0 257208  6240 ?        S    11:44   0:00 php app/service user
root      3005  0.0  0.0 485516  7816 ?        Ssl  11:44   0:00 php monitor: master    
root      3006  0.0  0.0 257208  6012 ?        S    11:44   0:00 php app/service monitor
root      3010  0.0  0.0 244896  7532 ?        S    11:44   0:00 php monitor: task      
root      3011  0.0  0.0 244896  7532 ?        S    11:44   0:00 php monitor: task      
root      3012  0.0  0.0 244896  7532 ?        S    11:44   0:00 php monitor: task      
root      3013  0.0  0.0 244896  7532 ?        S    11:44   0:00 php monitor: task      
root      3015  0.0  0.0 244896  7532 ?        S    11:44   0:00 php monitor: task      
root      3016  0.0  0.0 249284  7640 ?        S    11:44   0:00 php monitor: worker    
root      3017  0.0  0.0 249284  7640 ?        S    11:44   0:00 php monitor: worker    
root      5824  0.0  0.0 249284  7636 ?        S    14:11   0:00 php user: worker    
root      5825  0.0  0.0 249284  7636 ?        S    14:11   0:00 php user: worker    
root      5826  0.0  0.0 244896  7528 ?        S    14:11   0:00 php user: task      
root      5827  0.0  0.0 244896  7528 ?        S    14:11   0:00 php user: task      
root      5828  0.0  0.0 244896  7528 ?        S    14:11   0:00 php user: task      
root      5829  0.0  0.0 244896  7528 ?        S    14:11   0:00 php user: task      
root      5830  0.0  0.0 244896  7528 ?        S    14:11   0:00 php user: task      
root      6181  0.0  0.0 475292  5668 ?        Ssl  14:27   0:00 php http server: master  
root      6182  0.0  0.0 247108  4552 ?        S    14:27   0:00 php server.php -s restart
root      6186  0.0  0.0 252276 10992 ?        S    14:27   0:00 php http server: worker  
root      6187  0.0  0.0 249868  6884 ?        S    14:27   0:00 php http server: worker  
root      6227  0.0  0.0 105392   860 pts/8    S+   14:29   0:00 grep php
root     19549  0.0  0.0 138832  6648 ?        Ss   Nov08   0:01 php-fpm: master process (/usr/local/php71/etc/php-fpm.conf)                                                                        
www      19550  0.0  0.0 220688 14640 ?        S    Nov08   0:02 php-fpm: pool www                                                                                                                  
www      19551  0.0  0.0 219492 12548 ?        S    Nov08   0:01 php-fpm: pool www                           

服务都启动成功，数据表都创建好了，但是注册和登录失败

有什么方式可以排查问题出现在哪？请高手赐教。。。

**Comment by fucongcong** [comment]
1.查看runtime下的日志。看看有没有报错信息
2.进入src\Web\Controller\User\BaseController. 找到$service = (yield service_center('User'));
你dump($service) 看下返回的AsyncService对象

**Comment by fucongcong** [comment]
是有bug。在linux环境 区分大小写时候有个类找不到了。我稍后更新版本，你composer update一下就行了

**Comment by birdy0815** [comment]
update 了，也不行 

runtime 下没有出错日志，我怀疑服务根本没调用到。

打印信息如下：
Group\Async\AsyncService::__set_state(array( 'service' => 'User', 'serv' => NULL, 'port' => NULL, 'timeout' => 5, 'calls' => array ( ), 'callId' => 0, ))

**Comment by fucongcong** [comment]
中国镜像的话 你要稍微等一下。临时解决办法 vendor/group-co/framework/core/Group/SwooleKernal.php 第192行 $scheme = $address['scheme']; 修改为
$scheme = ucfirst($address['scheme']);

**Comment by birdy0815** [comment]
第二个文件应该是 vendor/group-co/framework/core/Group/Protocol/Server/Server.php

另外，搜索了一个 还有一个文件 
vendor/group-co/framework/core/Group/Process/HeartbeatProcess.php 第24行也需要修改

不过，修改完，以后，依然不行。

**Comment by birdy0815** [comment]
可以了，修改完，除了restart server，也要把serivce stop掉再启动，就OK了
